### ISSUE TITLE
No short code for event date

### ISSUE THREAD

**Issue by MaraRinn** [ESORaidplanner/ESORaidplanner#4]
I can create an event notification which will list the title, description and confirmed/backup attendees, but there's no date.

It would be nice to have a short code which will post the date and time as configured in the event.

**Comment by Woeler** [comment]
This would not make sense as the date and time of the event depends on what timezone the user is in. Since notifications can be sent to guilds with members all around the globe, a date/time string would not make sense at it would only be correct for a particular group of people.
