### ISSUE TITLE
Make event signups optional

### ISSUE THREAD

**Issue by dan-el** [ESORaidplanner/ESORaidplanner#85]
At the moment the raidplanner is designed to help plan raids including signups. 

The way I understand the raidplanner it could also easily be used as a "communication and management hub" for event planners. Let's say you run raids in the guild as well as "open events" and you still want to use the raidplanner (including discord/slack/telegram) to schedule all these events.

A checkbox could be implemented like "needs signups" which makes the signup part available to an event. This should of course also directly affect the bot notifications. E.g. no signups needed = no need to show that part of the notification (mainly to save space and focus on what's important)

**Comment by Woeler** [comment]
Closing this issue as I have added this option to v2.0.0

![image](https://user-images.githubusercontent.com/18422096/46962377-42935a80-d0a3-11e8-8900-a8cc7cdd875b.png)

**Comment by Woeler** [comment]
This can now be done by not using the fancy discord messages. I see no point in adding a `disable signup` option to the event entity. Since they are optional in the bot, signups can simply be ignored on the event, and in an extreme case, the event can simply be locked from the get go.
