### ISSUE TITLE
Display event tags in event description

### ISSUE THREAD

**Issue by dan-el** [ESORaidplanner/ESORaidplanner#87]
Can the event tags be added to the overview page of an event? Currently the tags are only visible in editing mode. It might be useful for event organizers or guild admins. Only saves one click, but it should be easy to implement.

**Comment by Woeler** [comment]
Closing this issue as this has been added to v2.0.0

![image](https://user-images.githubusercontent.com/18422096/46962708-162c0e00-d0a4-11e8-85e6-557322073147.png)
