### ISSUE TITLE
Make Discord bot event notifications even more configurable

### ISSUE THREAD

**Issue by dan-el** [ESORaidplanner/ESORaidplanner#88]
When using the placeholders to create a notification text the text appears as plain text in Discord (blue part in the image) and the "fancy discord box" is always there in a pre-defined format (red part).

Can the "fancy box" be made optional? Or configurable? This would give us more options and also reduce unnecessary double postings.

Image here: [https://imgur.com/4Z5fLx9](https://imgur.com/4Z5fLx9)

**Comment by Woeler** [comment]
Closing this issue as I have added this option to v2.0.0

![image](https://user-images.githubusercontent.com/18422096/46962377-42935a80-d0a3-11e8-8900-a8cc7cdd875b.png)
