### ISSUE TITLE
Change guild owner

### ISSUE THREAD

**Issue by claudioalbarran** [ESORaidplanner/ESORaidplanner#89]
Hello, we have a small and trhilling guild, regretably the person that was the owner of the guild has left for personal reasons, just leaving two admins but no other owner. Is there a way taht you can help us to promote any of the other admins? We'll be more than happy to provide additional details if needed

**Comment by Woeler** [comment]
Please give my the guild name, server and the name of the person that should be owner

**Comment by claudioalbarran** [comment]
Thank you for the quick reply sir! The guild is Rhaegal The Green and the owner should be claudio_albarran for now sir. Please let me know if anything else is needed

**Comment by Woeler** [comment]
Done.

**Comment by claudioalbarran** [comment]
Thank you!
