### ISSUE TITLE
Feature request: iCal export

### ISSUE THREAD

**Issue by dan-el** [ESORaidplanner/ESORaidplanner#90]
The headline says it: Can we have an ical export?

**Here is the idea:**
People's needs are ranging from A to Z. Some like calendars, some Discord, others don't mind logging in to the raidplanner.

* We are working on a new guild website and we are testing having a google calendar (for events) that links in with the new website (Wordpress with a plugin) - it displays nicely. And you can subscribe to the (publicly available) ical feed. Use your phone or Outlook or whatever.
* We are also testing the raidplanner because it's so well integrated with Discord (the bot) - most of our guild stuff happens on Discord.

But how to integrate the raidplanner events into the website or my calendar app on the phone? Yes, through an ical feed. With an ical feed the raidplanner events can be exported in a standardized way to numerous applications.

**Known limitations:**
* I guess the ical feed needs to be public unless you add OAuth or something similar to the raidplanner.

**Specifications:**
I think the following fields would make sense in an ical feed: DATE, TIME, DESCRIPTION, TAGS (?), LINK TO THE RAIDPLANNER EVENT PAGE
(Probably not the signups if the feed is public - data protection etc.)

**Wonderful result:**
Raidplanner feeding into Discord and our Website and any other app that can handle ical.

[https://icalendar.org/](https://icalendar.org/)

**Comment by Woeler** [comment]
Closing. This has been added to 2.0.0 both on a user and a guild level.
